### ISSUE TITLE
feat: wildcard support for aqua cp

### ISSUE THREAD

**Issue by lukasmrtvy** [aquaproj/aqua#1173]
## Feature Overview
Would be nice to support wildcard * in aqua cp.

## Why is the feature needed?
Install 3rd party binaries for OSs, similar to asdf-vm, useful when one is using more than one client device. 

## Does the feature include Breaking Changes?
No

## Example Code

```console
$ aqua cp * -o /usr/local/bin/
```

## Reference

- https://github.com/aquaproj/aqua/issues/1042#issuecomment-1237169166

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.
I think wildcard * isn't good because shell interprets wildcard as files in the current directories.

My idea is:

```console
$ aqua cp [-a] [<package name> ...]
```

- when packages are specified, only specified packages are copied
- when no package is specified, all packages in `aqua.yaml` are copied
- aqua reads multiple `aqua.yaml` recursively. `aqua cp` reads configuration files same as `aqua i`. This means by default `aqua cp` reads all configuration files except for global configuration files, and when `-a` option is set `aqua cp` reads all configuration files including global configuration files

**Comment by suzuki-shunsuke** [comment]
I've created a pull request for this issue.
https://github.com/aquaproj/aqua/pull/1247

**Comment by suzuki-shunsuke** [comment]
Published the prerelease version https://github.com/aquaproj/aqua/releases/tag/v1.20.0-0 .

**Comment by suzuki-shunsuke** [comment]
Released. https://github.com/aquaproj/aqua/releases/tag/v1.20.0
