### ISSUE TITLE
Would you support stable, nightly, LTS, or other versions with changing assets?

### ISSUE THREAD

**Issue by hituzi-no-sippo** [aquaproj/aqua#1515]
Hi, thank you for creating a great tool.

I use [Neovim with nightly](https://github.com/neovim/neovim/releases/tag/nightly).
However, Aqua does not support nightly.

Would Aqua specs support stable, nightly, or LTS versions where the asset changes over time?

It was not a bug, so the template was not used.

Sorry if it is correct to create this issue in [Aqua repository](https://github.com/aquaproj/aqua/issues/new/choose).

Thank you.

```console
$ cat aqua.yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   # https://aquaproj.github.io/docs/reference/checksum/
#   enabled: true
#   require_checksum: true
registries:
- type: standard
  ref: v3.115.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: neovim/neovim@nightly

$ aqua i
ERRO[0000] evaluate version constraints                  aqua_version=1.29.0 env=linux/amd64 error="evaluate the expression: Malformed version: nightly (
1:1)\n | semver(\">= 0.7.2\")\n | ^" package_name=neovim/neovim package_version=nightly program=aqua registry=standard registry_ref=v3.115.0
```

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.
I transferred this issue from aqua-registry to aqua because this issue is about the feature of aqua itself.

aqua doesn't support NeoVim's nightly build, because aqua assumes that the assets of the same version are immutable.
This is a design of aqua, so we won't change this.

You would be able to install nightly build by fixing `version_constraint` of the package `neovim/neovim` as the following.

https://github.com/aquaproj/aqua-registry/blob/baad0f57503251b694bb41a5946db17138ab419c/pkgs/neovim/neovim/registry.yaml#L22

```yaml
    version_constraint: Version == "nightly" or semver(">= 0.7.2")
```

But even if assets of nightly build are updated, aqua doesn't reinstall them.

Furthermore, if [Checksum Verification](https://aquaproj.github.io/docs/reference/checksum/) is enabled, you couldn't reinstall the nigthtly build even if you uninstall it unless you fix `aqua-checksums.json`.

**Comment by suzuki-shunsuke** [comment]
If versions of nightly build are changed per release, aqua would be able to support them.
For example, if versions of nightly build include timestamp or something (e.g. `nightly-20230103T185318`), they would be changed per release so aqua would be able to support them.

**Comment by suzuki-shunsuke** [comment]
aqua solves problems due to the difference of tool version by forcing to pin tool version.
You can unify tool versions in your team and CI.

Versioning which changes assets mutably doesn't fit with aqua spirit.

**Comment by hituzi-no-sippo** [comment]
Thank you for your response.

> Versioning which changes assets mutably doesn't fit with aqua spirit.

OK.

I will use [bob](https://github.com/MordechaiHadad/bob) to install NeoVim's nightly build.

> if versions of nightly build include timestamp or something (e.g. nightly-20230103T185318),

The version is different for each build. This is because it contains the commit ID.

This can be seen in the output of `nvim --version` or in [the Nightly release notes](https://github.com/neovim/neovim/releases/tag/nightly#:~:text=3a519d8-,NVIM,-v0.9.0%2Ddev%2D598).
The release name and tag name remain unchanged.
