### ISSUE TITLE
Registry search and gui 

### ISSUE THREAD

**Issue by gedw99** [aquaproj/aqua#1927]
Would be cool if the registry had a db site and search .

like nix has :)

was thinking it can be a simple go template thing and we can have the code in the cli so you can run it locally also for your local registry too .

**Comment by sheldonhull** [comment]
Curious. What would you see this being used for versus the aqua generate?

Since the aqua registry is continually updated, and the versions for cli tools in the aqua registry, only match the corresponding registry version, initially it seems like it could be confusing for new users. 

I think it's a cool idea though for approachability and raising more awareness for potential users over, trying to read a giant yaml file 😆

**Comment by gedw99** [comment]
thanks :)

can you point me to the code too ?  I wanted to fix a few things...

G
Location:     Berlin ( GMT+1)
Email:          ***@***.***
Mobile:        +4915231894553 ( linked to signal. telegram, facetime,
whatsapp )
Telegram:    http://t.me/gedw99
Signal:         https://signal.me/#p/+4915231894553
Booking:      https://www.cal.com/gedw99

**Comment by 4513ECHO** [comment]
Please create a issue or pull request to [my repository](https://github.com/4513ECHO/aqua-picker). Thanks.

**Comment by gedw99** [comment]
Hey @suzuki-shunsuke 

Multi language translation was what I was thinking.

**Comment by suzuki-shunsuke** [comment]
Oh, I see. Thanks.

**Comment by suzuki-shunsuke** [comment]
Unfortunately, I have no plan to support multi language translation and publish website for searching packages.
So I close this issue.
