### ISSUE TITLE
`aqua rm` doesn't seem to delete the `aqua-proxy` symlink

### ISSUE THREAD

**Issue by budimanjojo** [aquaproj/aqua#2613]
### aqua info

```console
$ aqua info
{
  "version": "2.21.3",
  "commit_hash": "8ddf104abfab2feb15018280c53ec9936aeff31e",
  "os": "linux",
  "arch": "amd64",
  "pwd": "/home/(USER)/.local/share/chezmoi",
  "root_dir": "/home/(USER)/.local/share/aquaproj-aqua",
  "env": {
    "AQUA_GLOBAL_CONFIG": "/home/(USER)/.config/aqua.yaml"
  },
  "config_files": []
}
```

### Overview

I delete a package using `aqua rm <package-name>` and doing `command -v <package-name>` still shows as `${HOME}/.local/share/aquaproj-aqua/bin/<package-name>`. But running `<package-name>` still works as expected which is falling back to the real path where the aqua unmanaged program is located. It's just a nuisance in my case.

### How to reproduce

aqua.yaml

```yaml

```

Other related code such as local Registry

```

```

Executed command and output

```console
$ 
```

### Debug output

```console
$ 
```

### Expected behaviour

`aqua-proxy` symlinked <package-name> should be removed from the `aqua` `/bin` directory.

### Actual behaviour

It's still there but it "re-routed" the package to where the `aqua` unmanaged program is located in $PATH which is good.

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.
This is not a bug but an expected behaviour.
As you said, even if symbolic links are remaining aqua fallback to executable files in PATH.
And you can get paths to them by `aqua which` command.
We intentionally keep links for lazy install.

I understand your opinion, so one idea is to add a command line option to remove symbolic links.

e.g.

```sh
aqua rm --remove-link cli/cli
```

I don't come up with a good option name.
`--remove-link` is ambiguous if only symbolic links are removed or both symbolic links and executable files are removed.

**Comment by budimanjojo** [comment]
Thanks for the reply! Didn't know there's `aqua which` command, pretty neat.
I'm fine with `--remove-link`, and I can't think of any possibility where you want to remove link and not the executable file? I usually wrong about things though so :laughing:

**Comment by budimanjojo** [comment]
I'm fine even without any new feature added too, maybe a note in the docs about this will also be fine.
Something like:
```
Removing a package doesn't remove the symbolic link because blablabla, you can remove the file manually if you want.
```

**Comment by suzuki-shunsuke** [comment]
We'll add the command line option to remove links from the `bin` directory.

- https://github.com/aquaproj/aqua/pull/3075
